#include "config_generator.hpp"

#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <ranges>
#include <stdexcept>

namespace hypr::cfg_autogen
{
    namespace detail
    {
        std::string GetDefaultConfigDir()
        {
            const char* home_dir = std::getenv("HOME");
            if (home_dir == nullptr)
            {
                throw std::runtime_error("env var $HOME does not exist");
            }

            std::filesystem::path dir = std::filesystem::path(home_dir) / ".config" / "hmon";
            std::filesystem::create_directories(dir);

            return dir.string();
        }

        std::string GenerateUniqueFilename(std::string_view extension)
        {
            // clang-format off
            auto nns_stamp = std::chrono::duration_cast<std::chrono::nanoseconds>(
                std::chrono::system_clock::now().time_since_epoch()
            ).count();
            // clang-format on

            return std::format("monitors_{}_generated.{}", nns_stamp, extension);
        }
    }  // namespace detail

    std::string GenerateLua(const std::vector<monitor::Monitor>& monitors)
    {
        if (std::empty(monitors)) return {};

        std::string   path = (std::filesystem::path(detail::GetDefaultConfigDir()) / detail::GenerateUniqueFilename(/* extension */ "lua"));
        std::ofstream ofstream(path);

        if (!ofstream.is_open())
        {
            throw std::runtime_error("failed to open file");
        }

        ofstream << "-- Generated by hmon\n\n";

        // clang-format off
        auto monitor2lua = [](const monitor::Monitor& monitor) constexpr -> std::string {
            return std::format(
                "hl.monitor({{\n"
                "    output = \"{}\",\n"
                "    disabled = {},\n"
                "    mode = \"{}x{}@{:.2f}\",\n"
                "    position = \"{}x{}\",\n"
                "    scale = {:.2f},\n"
                "}})\n\n",
                monitor.name_, monitor.disabled_, monitor.width_, monitor.height_, monitor.refresh_rate_, monitor.x_pos_, monitor.y_pos_, monitor.scale_
            );
        };
        // clang-format on

        std::ranges::copy(monitors | std::views::transform(monitor2lua), std::ostream_iterator<std::string>(ofstream));
        return path;
    }
}  // namespace hypr::cfg_autogen
